#!/usr/bin/env bash
#change_your_home_IP
#localhost_resolves_to_127.0.0.1_and_facebook.com_resolves_to_157.240.11.35
#localhost_resolves_to_127.0.0.2_and_facebook.com_resolves_to_8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
